const config = {
  apiUrl: "http://healthdeclare.hipe.com.vn:8181",
  CLIENT_URL: "http://healthdeclare.hipe.com.vn:8080",
  SCREEN_CODE: {
    ROLE_MANAGEMENT: "ROLE_MANAGEMENT",
    ADMIN_ACTION: "ADMIN_ACTION",
    USER_MANAGEMENT: "USER_MANAGEMENT",
    CLASS_MANAGEMENT: "CLASS_MANAGEMENT",
    TEACHER_MANAGEMENT: "TEACHER_MANAGEMENT",
    SYSTEM_CONFIG: "SYSTEM_CONFIG",
  },
  PERMISSION_SCREEN_MAP: {
    UserRoleManagement: "ROLE_MANAGEMENT",
  },
  LOGIN_URL: "http://healthdeclare.hipe.com.vn:8080/authenticate",
  DISPLAY_SCREEN_MAP: {
    ADMIN_ACTION: "HIEU_TRUONG,HIEU_PHO,GIAO_VIEN_CHU_NHIEM",
    USER_MANAGEMENT: "HIEU_TRUONG,HIEU_PHO,GIAO_VIEN_CHU_NHIEM",
    CLASS_MANAGEMENT: "HIEU_TRUONG,HIEU_PHO",
    TEACHER_MANAGEMENT: "HIEU_TRUONG,HIEU_PHO",
    SYSTEM_CONFIG: "HIEU_TRUONG",
  },
};
export default config;
